<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>gephi-plugin-parent</artifactId>
        <groupId>org.gephi</groupId>
        <version>0.10.0</version>
    </parent>

    <groupId>edu.buaa</groupId>
    <artifactId>tgraphdb</artifactId>
    <version>4.4.37</version>
    <packaging>nbm</packaging>

    <name>TGraphDB</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <gephi.version>0.10.0</gephi.version>
        <netbeans.version>RELEASE160</netbeans.version>
    </properties>

    <dependencies>
        <!-- Insert dependencies here -->
        <!-- dependence for new panel -->
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-awt</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-ui</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-windows</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-settings</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-lookup</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-dialogs</artifactId>
            <version>${netbeans.version}</version>
        </dependency>

        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>project-api</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>graph-api</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>tools-api</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>visualization-api</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>appearance-plugin</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>utils-longtask</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>datalab-api</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>preview-api</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>preview-plugin</artifactId>
            <version>${gephi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gephi</groupId>
            <artifactId>core-library-wrapper</artifactId>
            <version>0.10.0</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j</artifactId>
            <version>4.4.37-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.act</groupId>
            <artifactId>temporal-property-store</artifactId>
            <version>2.3.12-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.62</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.github.oshi</groupId>-->
<!--            <artifactId>oshi-core</artifactId>-->
<!--            <version>4.0.0</version>-->
<!--        </dependency>-->

        <!-- https://mvnrepository.com/artifact/com.graphhopper/graphhopper-reader-osm -->
<!--        <dependency>-->
<!--            <groupId>com.graphhopper</groupId>-->
<!--            <artifactId>graphhopper-reader-osm</artifactId>-->
<!--            <version>0.8.2</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.slf4j</groupId>-->
<!--                    <artifactId>slf4j-log4j12</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>log4j</groupId>-->
<!--                    <artifactId>log4j</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <configuration>
                    <licenseName>Apache 2.0</licenseName>
                    <author>Jinghe Song</author>
                    <publicPackages>
                        <!-- Insert public packages -->
                    </publicPackages>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <!-- Snapshot Repositories (only needed if developing against a SNAPSHOT version) -->
    <repositories>
        <repository>
            <id>oss-sonatype</id>
            <name>oss-sonatype</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>central</id>
            <name>Maven Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>
</project>


