/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.buaa.act.gephi.plugin.gui;

import static edu.buaa.act.gephi.plugin.gui.PluginStatus.*;

//import edu.buaa.act.gephi.plugin.preview.HeatMapStatisticPreview;
import edu.buaa.act.gephi.plugin.task.*;
import edu.buaa.act.gephi.plugin.tool.TimeDependentPathTool;
import edu.buaa.act.gephi.plugin.utils.GUIHook;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JSlider;
import javax.swing.JSpinner.DateEditor;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;

import org.gephi.graph.api.GraphController;
import org.gephi.graph.api.Node;
import org.gephi.project.api.ProjectController;
import org.gephi.utils.longtask.api.LongTaskExecutor;
import org.neo4j.graphdb.GraphDatabaseService;
import org.neo4j.graphdb.factory.GraphDatabaseFactory;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//edu.buaa.act.gephi.plugin.gui//TGraphDemoPanelTopComponent//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TGraphDemoPanelTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "rankingmode", openAtStartup = false)
@ActionID(category = "Window", id = "edu.buaa.act.gephi.plugin.gui.TGraphDemoPanelTopComponent")
@ActionReference(path = "Menu/Plugins" , position = 7333)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TGraphDemoPanelAction",
        preferredID = "TGraphDemoPanelTopComponent"
)
@Messages({
    "CTL_TGraphDemoPanelAction=TGraph Demo",
    "CTL_TGraphDemoPanelTopComponent=TGraph Demo",
    "HINT_TGraphDemoPanelTopComponent=Demonstration of TGraph DataBase: Traffic Data example."
})
public final class TGraphDemoPanelTopComponent extends TopComponent {

    private Component self;
    private GraphDatabaseService db;
    private String dbPath;
    private PluginStatus status=INIT;
    private int totalNodeCount = 0;
    private int totalEdgeCount = 0;
    
    
    public TGraphDemoPanelTopComponent() {
        initComponents();
        System.out.println("TopComponent init...");
        setName(Bundle.CTL_TGraphDemoPanelTopComponent());
        setToolTipText(Bundle.HINT_TGraphDemoPanelTopComponent());
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
        setUIStatus(INIT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TabbedPane_content = new javax.swing.JTabbedPane();
        Tab_import = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Button_import = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_subGraph = new javax.swing.JList();
        Button_findSubGraph = new javax.swing.JButton();
        Label_subGraphCount = new javax.swing.JLabel();
        Slider_importSpeed = new javax.swing.JSlider();
        Label_importSpeed = new javax.swing.JLabel();
        CheckBox_isDirectGraph = new javax.swing.JCheckBox();
        Tab_pathFinding = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_algorithms = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ToggleButton_chooseStartNode = new javax.swing.JToggleButton();
        Label_startNode = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ToggleButton_chooseEndNode = new javax.swing.JToggleButton();
        Label_endNode = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Slider_date = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        Spinner_hour = new javax.swing.JSpinner();
        Panel_resultColor = new javax.swing.JPanel();
        Button_runControl = new javax.swing.JButton();
        Tab_pathFinding1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Spinner_time = new javax.swing.JSpinner();
        Slider_time = new javax.swing.JSlider();
        Label_refreshTaskStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Button_connect = new javax.swing.JButton();
        Label_dbInfo = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(Button_import, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Button_import.text")); // NOI18N
        Button_import.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_importMouseClicked(evt);
            }
        });

        List_subGraph.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(List_subGraph);

        Button_findSubGraph.setLabel(org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Button_findSubGraph.label")); // NOI18N
        Button_findSubGraph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_findSubGraphMouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Label_subGraphCount, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Label_subGraphCount.text")); // NOI18N

        Slider_importSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider_importSpeedStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Label_importSpeed, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Label_importSpeed.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(CheckBox_isDirectGraph, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.CheckBox_isDirectGraph.text")); // NOI18N

        javax.swing.GroupLayout Tab_importLayout = new javax.swing.GroupLayout(Tab_import);
        Tab_import.setLayout(Tab_importLayout);
        Tab_importLayout.setHorizontalGroup(
            Tab_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_importLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(Tab_importLayout.createSequentialGroup()
                        .addComponent(Button_import)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckBox_isDirectGraph)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Tab_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Slider_importSpeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab_importLayout.createSequentialGroup()
                                .addComponent(Label_importSpeed)
                                .addGap(37, 37, 37))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tab_importLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_subGraphCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(Button_findSubGraph)))
                .addContainerGap())
        );
        Tab_importLayout.setVerticalGroup(
            Tab_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_importLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Tab_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Button_findSubGraph)
                    .addComponent(Label_subGraphCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Tab_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_importLayout.createSequentialGroup()
                        .addGroup(Tab_importLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_import)
                            .addComponent(CheckBox_isDirectGraph))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(Tab_importLayout.createSequentialGroup()
                        .addComponent(Slider_importSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_importSpeed)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        TabbedPane_content.addTab(org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Tab_import.TabConstraints.tabTitle"), Tab_import); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jLabel3.text")); // NOI18N

        ComboBox_algorithms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ToggleButton_chooseStartNode, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.ToggleButton_chooseStartNode.text")); // NOI18N
        ToggleButton_chooseStartNode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ToggleButton_chooseStartNodeItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Label_startNode, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Label_startNode.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ToggleButton_chooseEndNode, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.ToggleButton_chooseEndNode.text")); // NOI18N
        ToggleButton_chooseEndNode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ToggleButton_chooseEndNodeItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Label_endNode, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Label_endNode.text")); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jPanel4.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jLabel8.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jLabel10.text")); // NOI18N

        Spinner_hour.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1305422940000L), new java.util.Date(1305422820000L), new java.util.Date(1463275763123L), java.util.Calendar.HOUR));

        Panel_resultColor.setBackground(new java.awt.Color(255, 0, 51));
        Panel_resultColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_resultColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_resultColorLayout = new javax.swing.GroupLayout(Panel_resultColor);
        Panel_resultColor.setLayout(Panel_resultColorLayout);
        Panel_resultColorLayout.setHorizontalGroup(
            Panel_resultColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        Panel_resultColorLayout.setVerticalGroup(
            Panel_resultColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Spinner_hour, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel_resultColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Slider_date, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Slider_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(Spinner_hour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panel_resultColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.openide.awt.Mnemonics.setLocalizedText(Button_runControl, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Button_runControl.text_1")); // NOI18N
        Button_runControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_findShortestPathMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Tab_pathFindingLayout = new javax.swing.GroupLayout(Tab_pathFinding);
        Tab_pathFinding.setLayout(Tab_pathFindingLayout);
        Tab_pathFindingLayout.setHorizontalGroup(
            Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_pathFindingLayout.createSequentialGroup()
                .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Tab_pathFindingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tab_pathFindingLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox_algorithms, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Tab_pathFindingLayout.createSequentialGroup()
                                .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_endNode)
                                    .addComponent(Label_startNode))
                                .addGap(35, 35, 35)
                                .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ToggleButton_chooseStartNode)
                                    .addComponent(ToggleButton_chooseEndNode))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Tab_pathFindingLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_runControl)))
                .addContainerGap())
        );
        Tab_pathFindingLayout.setVerticalGroup(
            Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_pathFindingLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ComboBox_algorithms, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_startNode)
                        .addComponent(ToggleButton_chooseStartNode, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tab_pathFindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_endNode)
                        .addComponent(ToggleButton_chooseEndNode, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_runControl)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        TabbedPane_content.addTab(org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Tab_pathFinding.TabConstraints.tabTitle"), Tab_pathFinding); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jPanel5.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        Spinner_time.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1305422940000L), new java.util.Date(1305422820000L), new java.util.Date(1463275763123L), java.util.Calendar.HOUR));

        Slider_time.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Slider_timeStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Label_refreshTaskStatus, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Label_refreshTaskStatus.text")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Slider_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Spinner_time, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_refreshTaskStatus)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Slider_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spinner_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_refreshTaskStatus))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Tab_pathFinding1Layout = new javax.swing.GroupLayout(Tab_pathFinding1);
        Tab_pathFinding1.setLayout(Tab_pathFinding1Layout);
        Tab_pathFinding1Layout.setHorizontalGroup(
            Tab_pathFinding1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_pathFinding1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        Tab_pathFinding1Layout.setVerticalGroup(
            Tab_pathFinding1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tab_pathFinding1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        TabbedPane_content.addTab(org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Tab_pathFinding1.TabConstraints.tabTitle"), Tab_pathFinding1); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.jLabel1.text")); // NOI18N

        Button_connect.setLabel(org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Button_connect.label")); // NOI18N
        Button_connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_connectMouseClicked(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(Label_dbInfo, org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.Label_dbInfo.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_dbInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_connect)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TabbedPane_content, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_connect)
                    .addComponent(Label_dbInfo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane_content, javax.swing.GroupLayout.PREFERRED_SIZE, 274, Short.MAX_VALUE))
        );

        TabbedPane_content.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(TGraphDemoPanelTopComponent.class, "TGraphDemoPanelTopComponent.TabbedPane_content.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_connectMouseClicked
        if(status==INIT){
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.setFileFilter(new TGraphDatabaseFolderFilter());
            jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            File dbDir;
            if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                dbDir = jFileChooser.getSelectedFile();
                if (dbDir.exists()) {
                    db = getTGraphInstance(dbDir.getAbsolutePath());
//                    HeatMapStatisticPreview preview = Lookup.getDefault().lookup(HeatMapStatisticPreview.class);
//                    preview.setDB(db);
                    final FindSeparateSubGraphAsyncTask subgraphTask = new FindSeparateSubGraphAsyncTask(db, totalNodeCount);
                    subgraphTask.onFinish(new GUIHook<List<FindSeparateSubGraphAsyncTask.IsolatedNetworkInfo>>(){
                        public void guiHandler(List<FindSeparateSubGraphAsyncTask.IsolatedNetworkInfo> value) {
                            DefaultListModel model = new DefaultListModel();
                            for(FindSeparateSubGraphAsyncTask.IsolatedNetworkInfo info: value){
                                model.addElement(info.getNodeCount()+" nodes. Start node id "+info.getStartNodeId());
                            }
                            List_subGraph.setVisibleRowCount(7);
                            List_subGraph.setModel(model);
                            Label_subGraphCount.setText(value.size()+" found");
                            setUIStatus(SUBNET_FOUND);
                        }
                    });
                    
                    GetTGraphDatabaseInfoAsyncTask connectTask = new GetTGraphDatabaseInfoAsyncTask(db);
                    connectTask.onFinish(new GUIHook<Map<String, String>>() {
                        @Override
                        public void guiHandler(Map<String, String> value) {
                            if (value != null) {
                                Label_dbInfo.setText(
                                        "nodes:" + value.get("node-count") + " edges:" + value.get("edge-count")
                                );
                                totalNodeCount = Integer.parseInt(value.get("node-count"));
                                totalEdgeCount = Integer.parseInt(value.get("edge-count"));
                                setUIStatus(DB_READY);
                                new LongTaskExecutor(true).execute(subgraphTask, subgraphTask,"Find Unconnected subgraphs...",null);
                            }
                        }
                    });
                    new LongTaskExecutor(true).execute(connectTask, connectTask, "connecting...", null);
                } else {
                    notice("dir not found!");
                }
            }
        }else{
            if(confirm("Disconnect from TGraph?")){
                if(db!=null) db.shutdown();
                db=null;
                dbPath=null;
                setUIStatus(INIT);
            }
        }
    }//GEN-LAST:event_Button_connectMouseClicked

    private void Button_findSubGraphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_findSubGraphMouseClicked
        if(status.value()>= DB_READY.value()){
            FindSeparateSubGraphAsyncTask task = new FindSeparateSubGraphAsyncTask(db, totalNodeCount);
            task.onFinish(new GUIHook<List<FindSeparateSubGraphAsyncTask.IsolatedNetworkInfo>>(){
                public void guiHandler(List<FindSeparateSubGraphAsyncTask.IsolatedNetworkInfo> value) {
                    DefaultListModel model = new DefaultListModel();
                    for(FindSeparateSubGraphAsyncTask.IsolatedNetworkInfo info: value){
                        model.addElement(info.getNodeCount()+" nodes. Start node id "+info.getStartNodeId());
                    }
                    List_subGraph.setVisibleRowCount(7);
                    List_subGraph.setModel(model);
                    Label_subGraphCount.setText(value.size()+" found");
                    setUIStatus(SUBNET_FOUND);
                }
            });
            new LongTaskExecutor(true).execute(task, task,"Find Unconnected subgraphs...",null);
        }else{
            notice("Please connect to TGraph database first.");
        }
    }//GEN-LAST:event_Button_findSubGraphMouseClicked

    private NetworkImportAsyncTask netImportTask;
    private void Button_importMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_importMouseClicked
        if(status.value()>=SUBNET_FOUND.value()){
            String selectText = (String) List_subGraph.getSelectedValue();
            if(selectText!=null){
                ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
                if (pc.getCurrentProject() == null) {
                    notice("no project");
                }
                GraphController gc = Lookup.getDefault().lookup(GraphController.class);
                long nodeId = Long.valueOf(selectText.substring(selectText.lastIndexOf(" ")+1,selectText.length()));
                int nodeCount = Integer.valueOf(selectText.substring(0,selectText.indexOf(" ")));
//                System.out.println(nodeId+" "+nodeCount);
                netImportTask = new NetworkImportAsyncTask(
                        db,
                        gc.getGraphModel(),
                        nodeId,
                        nodeCount,
                        Slider_importSpeed.getValue()/10f,
                        CheckBox_isDirectGraph.isSelected()                        
                );
                netImportTask.onFinish(new GUIHook<Integer>(){
                    public void guiHandler(Integer value) {
                        notice("import "+value+" nodes");
                        setUIStatus(NET_IMPORTED);
                    }
                });
                new LongTaskExecutor(true).execute(netImportTask,netImportTask,"importing...",null);
            }else{
                notice("Pleae select subgraph to import.");
            }
        }else{
            notice("should find subgraph first.");
        }
    }//GEN-LAST:event_Button_importMouseClicked

    private int realTimeFormatConvert(Date t){
        Calendar time = Calendar.getInstance();
        time.setTime(t);
        int month = time.get(Calendar.MONTH);
        int day = time.get(Calendar.DAY_OF_MONTH);
        int hour = time.get(Calendar.HOUR_OF_DAY);
        int minute = time.get(Calendar.MINUTE);
        String timeStr = "11"+String.format("%02d",month)+
                String.format("%02d",day)+String.format("%02d",hour)+
                String.format("%02d",minute);
        return Integer.parseInt(timeStr);
    }
    
    private int dateTimeConvert(Date t){
        long t0 = t.getTime();
        return (int) (t0/1000);
    }
    
    private String time2String(int t){
        return t+"";
    }
    
    private void Button_findShortestPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_findShortestPathMouseClicked
        SpinnerModel model = Spinner_hour.getModel();
        if(model instanceof SpinnerDateModel){
            GraphController gc = Lookup.getDefault().lookup(GraphController.class);
            long startNodeTGraphId = (Long) startNode.getAttribute("tgraph_id");
            long endNodeTGraphId = (Long) endNode.getAttribute("tgraph_id");
            int time = dateTimeConvert(((SpinnerDateModel) model).getDate());
            TimeDependentDijkstraOneTransactionAsyncTask task =  new TimeDependentDijkstraOneTransactionAsyncTask(
                    db,
                    gc.getGraphModel(),
                    startNodeTGraphId,
                    endNodeTGraphId,
                    time,
                    Panel_resultColor.getBackground()){
                public void onResult(long searchNodeCount, List<Long> path, List<Integer> arriveTimes){
                    String result="search "+searchNodeCount+" nodes. ";
                    for(int i=0;i<path.size();i++){
                        result+= (path.get(i)+"["+time2String(arriveTimes.get(i))+"]-->\n");
                    }
                    notice(result);
                }
            };
            new LongTaskExecutor(true).execute(task, task);
        }
    }//GEN-LAST:event_Button_findShortestPathMouseClicked

    private void ToggleButton_chooseStartNodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ToggleButton_chooseStartNodeItemStateChanged
        TimeDependentPathTool tool = Lookup.getDefault().lookup(TimeDependentPathTool.class);
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(tool.setUIStatus("start")){
                setUIStatus(CHOOSING_START);
            }else{
                ToggleButton_chooseStartNode.setSelected(false);
                notice("Please press tool icon first.");
            }
        }else{
            setUIStatus(NET_IMPORTED);
            startNode = tool.getStartNode();
            if(startNode!=null){
                Label_startNode.setText("node["+startNode.getAttribute("tgraph_id")+"]");                
            }else{
                notice("start node not selected.");
            }
        }
    }//GEN-LAST:event_ToggleButton_chooseStartNodeItemStateChanged

    private void ToggleButton_chooseEndNodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ToggleButton_chooseEndNodeItemStateChanged
        TimeDependentPathTool tool = Lookup.getDefault().lookup(TimeDependentPathTool.class);
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(tool.setUIStatus("end")){
                setUIStatus(CHOOSING_END);
            }else{
                ToggleButton_chooseEndNode.setSelected(false);
                notice("Please press tool icon first.");
            }
        }else{
            setUIStatus(NET_IMPORTED);
            endNode = tool.getEndNode();
            if(endNode!=null){
                Label_endNode.setText("node["+endNode.getAttribute("tgraph_id")+"]");                
            }else{
                notice("end node not selected.");
            }
        }
    }//GEN-LAST:event_ToggleButton_chooseEndNodeItemStateChanged

    private void Slider_importSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider_importSpeedStateChanged
        JSlider source = (JSlider)evt.getSource();
        if (!source.getValueIsAdjusting()) { // when dragging: do nothing; when release: go following lines.
            int speed = (int)source.getValue();
            Label_importSpeed.setText("Speed: "+(speed/10f)+"x");
            if(netImportTask!=null){
                netImportTask.setImportSpeed(speed/10f);
            }
        }
    }//GEN-LAST:event_Slider_importSpeedStateChanged

    private void Slider_timeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Slider_timeStateChanged
        JSlider source = (JSlider)evt.getSource();
        int timeStamp = Slider_time.getValue();
        if (source.getValueIsAdjusting()) { // when dragging: only update time label
            Date time = new Date(timeStamp*1000L);
            model.setValue(time);
        }else if(status.value()>INIT.value()){// when release: start connectTask.
            Label_refreshTaskStatus.setText("updating...");
            GraphController gc = Lookup.getDefault().lookup(GraphController.class);
            UpdateGraphStatusAsyncTask task = new UpdateGraphStatusAsyncTask(db,gc.getGraphModel().getGraph(),timeStamp);
            task.onFinish(new GUIHook<Integer>(){
                public void guiHandler(Integer value) {
                    Label_refreshTaskStatus.setText("done");
                }
            });
            new LongTaskExecutor(true).execute(task,task,"refreshing...",null);
        }
    }//GEN-LAST:event_Slider_timeStateChanged

    private void Panel_resultColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_resultColorMouseClicked
        Color newColor = JColorChooser.showDialog(this, "Choose Color of Shortest Path",Panel_resultColor.getBackground());
        if(newColor!=null){
            Panel_resultColor.setBackground(newColor);
        }
    }//GEN-LAST:event_Panel_resultColorMouseClicked

    private Node startNode;
    private Node endNode;
    public void onNodeClick(Node[] nodes, String status){
        if(nodes.length>0){
            setUIStatus(NET_IMPORTED);
            if(status.equals("start")){
                startNode = nodes[0];
                Label_startNode.setText("node["+startNode.getAttribute("tgraph_id")+"]");
            }else if(status.equals("end")){
                endNode = nodes[0];
                Label_endNode.setText("node["+endNode.getAttribute("tgraph_id")+"]");
            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_connect;
    private javax.swing.JButton Button_findSubGraph;
    private javax.swing.JButton Button_import;
    private javax.swing.JButton Button_runControl;
    private javax.swing.JCheckBox CheckBox_isDirectGraph;
    private javax.swing.JComboBox ComboBox_algorithms;
    private javax.swing.JLabel Label_dbInfo;
    private javax.swing.JLabel Label_endNode;
    private javax.swing.JLabel Label_importSpeed;
    private javax.swing.JLabel Label_refreshTaskStatus;
    private javax.swing.JLabel Label_startNode;
    private javax.swing.JLabel Label_subGraphCount;
    private javax.swing.JList List_subGraph;
    private javax.swing.JPanel Panel_resultColor;
    private javax.swing.JSlider Slider_date;
    private javax.swing.JSlider Slider_importSpeed;
    private javax.swing.JSlider Slider_time;
    private javax.swing.JSpinner Spinner_hour;
    private javax.swing.JSpinner Spinner_time;
    private javax.swing.JPanel Tab_import;
    private javax.swing.JPanel Tab_pathFinding;
    private javax.swing.JPanel Tab_pathFinding1;
    private javax.swing.JTabbedPane TabbedPane_content;
    private javax.swing.JToggleButton ToggleButton_chooseEndNode;
    private javax.swing.JToggleButton ToggleButton_chooseStartNode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        if(dbPath==null || db==null){
            setUIStatus(INIT);
        }
    }

    @Override
    public void componentClosed() {
        System.out.println("component close");
//        if(confirm("Disconnect from TGraph?")){
//            if(db!=null) db.shutdown();
//            db=null;
//            dbPath=null;
//            setUIStatus(INIT);
//        }
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    private void notice(String s) {
        DialogDisplayer.getDefault().notify(new NotifyDescriptor.Message(s));
    }
    
    private boolean confirm(String s){
        if(DialogDisplayer.getDefault().notify(new NotifyDescriptor.Confirmation(s,NotifyDescriptor.OK_CANCEL_OPTION)) == NotifyDescriptor.OK_OPTION){
            return true;
        } else {
            return false;
        }
    }
    
    private GraphDatabaseService getTGraphInstance(String absolutePath) {
        if (db == null) {
            dbPath = absolutePath;
            db = new GraphDatabaseFactory()
                    .newEmbeddedDatabaseBuilder(absolutePath)
                    .loadPropertiesFromFile("")
                    .newGraphDatabase();
        }
        return db;
    }
    
    
    SpinnerDateModel model;
    private void setUIStatus(PluginStatus status){
        this.status = status;
        System.out.println(this.status);
        switch(status){
            case INIT:
                Label_dbInfo.setText("not connected.");
                Button_connect.setText("Connect");
                Button_findSubGraph.setEnabled(false);
                Button_import.setEnabled(false);
                TabbedPane_content.setSelectedIndex(0);
                TabbedPane_content.setEnabled(false);
                List_subGraph.setModel(new javax.swing.AbstractListModel() {
                    public int getSize() { return 0; }
                    public Object getElementAt(int i) { return null; }
                });
                List_subGraph.setEnabled(false);
                Label_subGraphCount.setText("");
                ComboBox_algorithms.removeAllItems();
                ComboBox_algorithms.addItem("Time Dependent Dijkstra");
                ComboBox_algorithms.addItem("Time Dependent A*");
                ComboBox_algorithms.addItem("Time Dependent ALT");
                ComboBox_algorithms.addItem("Dijkstra");
                Slider_date.setMinimum(0);
                Slider_date.setMaximum(100);
                Label_startNode.setText("");
                Label_endNode.setText("");
                Slider_importSpeed.setMinimum(1);
                Slider_importSpeed.setMaximum(10);
                Calendar calendar = Calendar.getInstance();
                calendar.set(2010,11-1,4,1,5);
                Date start = calendar.getTime();
                calendar.set(2010,11-1,4,23,55);
                Date end = calendar.getTime();
                model = new SpinnerDateModel(start,start,end, Calendar.MINUTE);
                model.setCalendarField(Calendar.MINUTE);
                Spinner_hour.setModel(model);
                Spinner_hour.setEditor(new DateEditor(Spinner_hour, "yyyy-MM-dd HH:mm"));
                Spinner_time.setModel(model);
                Spinner_time.setEditor(new DateEditor(Spinner_time, "yyyy-MM-dd HH:mm"));
                Slider_time.setMinimum((int) (start.getTime()/1000));
                Slider_time.setMaximum((int) (end.getTime()/1000));
                Slider_time.setValue((int) ((start.getTime()+end.getTime())/2000));
                break;
            case DB_READY:
                Button_connect.setText("Disconnect");
                Button_findSubGraph.setEnabled(true);
                Button_import.setEnabled(false);
                TabbedPane_content.setEnabled(true);
                Tab_import.setEnabled(true);
                Tab_pathFinding.setEnabled(false);
                break;
            case SUBNET_FOUND:
                List_subGraph.setEnabled(true);
                Button_import.setEnabled(true);
                break;
            case NET_IMPORTED://eg. ready for path finding.
                TabbedPane_content.setEnabled(true);
                ToggleButton_chooseStartNode.setSelected(false);
                ToggleButton_chooseEndNode.setSelected(false);
                ToggleButton_chooseStartNode.setText("choose");
                ToggleButton_chooseEndNode.setText("choose");
                break;
            case CHOOSING_START:
                ToggleButton_chooseStartNode.setText("done");
//                ToggleButton_chooseStartNode.
                break;
            case CHOOSING_END:
                ToggleButton_chooseEndNode.setText("done");
                break;
        }
    }
    
    
}
